---

- name: "Create monitors for all errors"
  include_tasks: monitor-all-errors.yml
  loop: "{{ queue | json_query(query) }}"
  vars:
    query: "[?type=='error']"

- name: "Create monitor for test_devops_new_houses queue"
  include_tasks: monitor-team1-2.yml
  loop: "{{ queue | json_query(query) }}"
  vars:
    query: "[?name=='test_devops_new_houses']"

- name: "Create monitor for test_devops_makelaars queue"
  include_tasks: monitor-team1-2.yml
  loop: "{{ queue | json_query(query) }}"
  vars:
    query: "[?name=='test_devops_makelaars']"

- name: "Create monitors for team3"
  include_tasks: monitor-team3.yml
  loop: "{{ queue | json_query(query) }}"
  vars:
    query: "[?type=='standard']"
